In [4]:
from datetime import datetime, date, time 

dt = datetime(2011,10,29,20,30,21)

dt.year

2011

In [7]:
dt.strftime('%m/%d/%Y')

'10/29/2011'

In [8]:
dt.replace(minute = 0, second = 0)

datetime.datetime(2011, 10, 29, 20, 0)

In [15]:
dt2=datetime.today()

delta=dt2-dt

delta

datetime.timedelta(days=3344, seconds=7245, microseconds=48235)

In [18]:
x=2

value = 3 if x==3 else 'not 3'

In [19]:
value

'not 3'

In [24]:
a= 'Esto es un string que te parece'
tup_a=tuple(a)
tup_a.count('e')

5

In [27]:
a = [2,3,1,34,5]

[1, 2, 3, 5, 34]

In [4]:
def f():
    a = 5
    b = 6
    c = 7
    return {'a' : a, 'b' : b, 'c' : c}

o,y,e= f()



'c'

In [5]:
x = ['foo','card','bar','aaaa','abab']
len(set(list(x)))

5

In [1]:
import numpy as np
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

In [2]:
# Selecting two of the three names to combine multiple boolean conditions, use
# boolean arithmetic operators like & (and) and | (or):

mask = (names == 'Bob') | (names == 'Will')
mask

array([ True, False,  True,  True,  True, False, False])

In [11]:
xarr= np.arange(7)
xarr

array([0, 1, 2, 3, 4, 5, 6])

In [9]:
yarr= np.arange(7)
yarr += 7
yarr

array([ 7,  8,  9, 10, 11, 12, 13])

In [17]:
xs,ys = np.meshgrid(xarr,xarr)