In [2]:
import pandas as pd 
import numpy as np

In [4]:
from datetime import datetime, date, time 

dt = datetime(2011,10,29,20,30,21)

dt.year

2011

In [7]:
dt.strftime('%m/%d/%Y')

'10/29/2011'

In [8]:
dt.replace(minute = 0, second = 0)

datetime.datetime(2011, 10, 29, 20, 0)

In [15]:
dt2=datetime.today()

delta=dt2-dt

delta

datetime.timedelta(days=3344, seconds=7245, microseconds=48235)

In [18]:
x=2

value = 3 if x==3 else 'not 3'

In [19]:
value

'not 3'

In [24]:
a= 'Esto es un string que te parece'
tup_a=tuple(a)
tup_a.count('e')

5

In [27]:
a = [2,3,1,34,5]

[1, 2, 3, 5, 34]

In [4]:
def f():
    a = 5
    b = 6
    c = 7
    return {'a' : a, 'b' : b, 'c' : c}

o,y,e= f()



'c'

In [5]:
x = ['foo','card','bar','aaaa','abab']
len(set(list(x)))

5

In [1]:
import numpy as np
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

In [2]:
# Selecting two of the three names to combine multiple boolean conditions, use
# boolean arithmetic operators like & (and) and | (or):

mask = (names == 'Bob') | (names == 'Will')
mask

array([ True, False,  True,  True,  True, False, False])

In [11]:
xarr= np.arange(7)
xarr

array([0, 1, 2, 3, 4, 5, 6])

In [9]:
yarr= np.arange(7)
yarr += 7
yarr

array([ 7,  8,  9, 10, 11, 12, 13])

In [17]:
xs,ys = np.meshgrid(xarr,xarr)

In [1]:
import pandas as pd
df = pd.DataFrame(['A+', 'A', 'A-', 'B+', 'B', 'B-', 'C+', 'C', 'C-', 'D+', 'D'], index=['excellent', 'excellent', 'excellent', 'good', 'good', 'good', 'ok', 'ok', 'ok', 'poor', 'poor'], columns = ['Grades'])

In [2]:
df

Grades
excellent     A+
excellent      A
excellent     A-
good          B+
good           B
good          B-
ok            C+
ok             C
ok            C-
poor          D+
poor           D

In [4]:
my_categories=pd.CategoricalDtype(categories =['A+', 'A', 'A-', 'B+', 'B', 'B-', 'C+', 'C', 'C-', 'D+', 'D'], ordered = True)

AttributeError: module 'pandas' has no attribute 'CategoricalDtype'

In [11]:
(pd.Timestamp('11/29/2019')+ pd.offsets.MonthEnd()).weekday()

5

In [20]:
import numpy as np
df = pd.DataFrame({'key':['a','b','c']*4,
                   'value': np.arange(12.)})
g = df.groupby('key').value.mean()
g

key
a    4.5
b    5.5
c    6.5
Name: value, dtype: float64

In [18]:
g.transform(lambda x: x.rank(ascending=False))

key
a    3.0
b    2.0
c    1.0
Name: value, dtype: float64

In [21]:
g.transform('mean')

ValueError: transforms cannot produce aggregated results

In [22]:
g.transform(lambda x: x.mean())

ValueError: transforms cannot produce aggregated results

In [3]:
students_df = pd.DataFrame([{'id':'1200', 'Name': 'Kelly', 'School': 'Architecture'},
                          {'id':'1201','Name': 'Sally', 'School':'Architecture'},
                          {'id':'1202','Name': 'James', 'School': 'Business'},
                          {'id':'1203','Name': 'Brad', 'School': 'Business'},
                          {'id':'1204','Name': 'John', 'School': 'Engineering'},
                          {'id':'1205','Name': 'Paul', 'School': 'Engineering'}])
students_df

Name        School    id
0  Kelly  Architecture  1200
1  Sally  Architecture  1201
2  James      Business  1202
3   Brad      Business  1203
4   John   Engineering  1204
5   Paul   Engineering  1205

In [47]:
quiz_df = pd.DataFrame([{'id':'1202', 'score':'93'},
                        {'id':'1205', 'score':'95'},
                        {'id':'1203', 'score':'86'},
                        {'id':'1201', 'score':'75'},
                        {'id':'1568', 'score':'68'},
                        {'id':'1532', 'score':'80'}])
quiz_df

id score
0  1202    93
1  1205    95
2  1203    86
3  1201    75
4  1568    68
5  1532    80

In [39]:
pd.merge(students_df,quiz_df,how = 'inner', on='id').set_index('id')

Name        School score
id                             
1201  Sally  Architecture    75
1202  James      Business    93
1203   Brad      Business    86
1205   Paul   Engineering    95

In [48]:
pd.merge(students_df, quiz_df, how = 'inner',  on='id').set_index('id')

Name        School score
id                             
1201  Sally  Architecture    75
1202  James      Business    93
1203   Brad      Business    86
1205   Paul   Engineering    95

In [49]:
pd.merge(students_df, quiz_df, how = 'left',  on='id').set_index('id')

Name        School score
id                             
1200  Kelly  Architecture   NaN
1201  Sally  Architecture    75
1202  James      Business    93
1203   Brad      Business    86
1204   John   Engineering   NaN
1205   Paul   Engineering    95

In [50]:
pd.merge(students_df, quiz_df, how = 'outer',  on='id').set_index('id')

Name        School score
id                             
1200  Kelly  Architecture   NaN
1201  Sally  Architecture    75
1202  James      Business    93
1203   Brad      Business    86
1204   John   Engineering   NaN
1205   Paul   Engineering    95
1568    NaN           NaN    68
1532    NaN           NaN    80

In [51]:
pd.merge(students_df, quiz_df, how = 'inner', on='id')

Name        School    id score
0  Sally  Architecture  1201    75
1  James      Business  1202    93
2   Brad      Business  1203    86
3   Paul   Engineering  1205    95

In [53]:
pd.merge(students_df, quiz_df, how = 'inner', left_index = True, right_index = True)

Name        School  id_x  id_y score
0  Kelly  Architecture  1200  1202    93
1  Sally  Architecture  1201  1205    95
2  James      Business  1202  1203    86
3   Brad      Business  1203  1201    75
4   John   Engineering  1204  1568    68
5   Paul   Engineering  1205  1532    80

In [5]:
students_df

Name        School    id
0  Kelly  Architecture  1200
1  Sally  Architecture  1201
2  James      Business  1202
3   Brad      Business  1203
4   John   Engineering  1204
5   Paul   Engineering  1205

In [7]:
students_df.replace({'Sally':'Jesus',
                    'James':'Brandom'}, inplace = True)
students_df

Name        School    id
0    Kelly  Architecture  1200
1    Jesus  Architecture  1201
2  Brandom      Business  1202
3     Brad      Business  1203
4     John   Engineering  1204
5     Paul   Engineering  1205

In [11]:
students_df=students_df.set_index('School')

In [12]:
students_df

Name    id
School                     
Architecture    Kelly  1200
Architecture    Jesus  1201
Business      Brandom  1202
Business         Brad  1203
Engineering      John  1204
Engineering      Paul  1205

In [1]:
import pandas as pd
A = pd.DataFrame(['Vietnam','United States','Iran','South Korea'],index = range(4))
B = pd.DataFrame(['Viet nam','United States','Iran','Korea','Japan'],index = range(5))
C = pd.DataFrame(['Viet nam','United States','Iran','Indonesia'])
A.rename(columns={0:'Country'},inplace=True)
B.rename(columns={0:'Country Name'},inplace=True)
C.rename(columns={0:'Country Name'},inplace=True)                  
D = pd.merge(A,B,how='outer',left_on='Country',right_on='Country Name')
E = pd.merge(C,D,how='outer',left_on='Country Name',right_on='Country')
D1 = pd.merge(A,B,how='inner',left_on='Country',right_on='Country Name')
E1 = pd.merge(C,D1,how='inner',left_on='Country Name',right_on='Country')
print(len(E)-len(E1))
print(len(E))
print(len(E1))

B.rename(columns={'Country Name':'Country'},inplace=True)
C.rename(columns={'Country Name':'Country'},inplace=True) 
D = pd.merge(A,B,how='outer',left_on='Country',right_on='Country')
E = pd.merge(C,D,how='outer',left_on='Country',right_on='Country')
D1 = pd.merge(A,B,how='inner',on ='Country')
E1 = pd.merge(C,D1,how='inner',on='Country')
print(len(E)-len(E1))
print(len(E))
print(len(E1))

7
9
2
6
8
2
