In [3]:
import numpy as np

def create_board():
    """creates 3 x3 numpy array"""
    board=np.zeros((3,3))
    return(board)



In [4]:
def random_place(board,player):
    """ places a marker for the current player (1 or 2) at random among all positions with value 0 in board """
    import random
    selection=possibilities(board)
    position=random.choice(selection)
    board=place(board,player,position)
    return(board)

In [11]:
def random_place(board,player):
    """ places a marker for the current player (1 or 2) at random among all positions with value 0 in board """
    import random
    selection=possibilities(board)
    position=random.choice(selection)
    board=place(board,player,position)
    return(board)
x

In [12]:
import numpy as np

def create_board():
    """creates 3 x3 numpy array"""
    board=np.zeros((3,3))
    return(board)

In [15]:
x=create_board()

In [16]:
random_place(x,1)

NameError: name 'possibilities' is not defined

In [18]:
import numpy as np

def create_board():
    """creates 3 x3 numpy array"""
    board=np.zeros((3,3))
    return(board)

In [19]:
def place(board,player,position):
    """ Allows placement of player 1 or 2 on empty (corresponding to (0,0) position on board """
    if board[position]==0 and (player==1 or player==2):
        board[position]=player
    return(board)

In [20]:
def possibilities(board):
    """" Find all positions (as tuples), where numpy array board is 0, returns tuples as list """
    positions=np.array(np.where(board==0)).T #only arrays can be transposed, np.where returns tuple
    list_of_tuples=list(map(tuple,positions))
    return(list_of_tuples)

In [21]:
def random_place(board,player):
    """ places a marker for the current player (1 or 2) at random among all positions with value 0 in board """
    import random
    selection=possibilities(board)
    position=random.choice(selection)
    board=place(board,player,position)
    return(board)

In [22]:
#Exercise 5
board = create_board()
for j in range(3):
    for player in [1,2]:
        board=random_place(board,player)
print(board)

[[1. 2. 1.]
 [0. 0. 0.]
 [1. 2. 2.]]


In [24]:
#Exercise 6
def row_win(board, player):
    for i in range(board.shape[0]):
        if (set(board[i,:]) == {player})==True:
            return(True)
    return(False)
row_win(board,1)

False

In [25]:
def col_win(board, player):
    for i in range(board.shape[0]):
        if (set(board[:,i]) == {player})==True:
            return(True)
    return(False)

In [27]:
#Exercise 8
def diag_win(board, player):
    for i in range(board.shape[1]):
        if (set(np.diagonal(board)) == {player})==True:
            return(True)
    return(False)

diag_win(board, 1)


False

In [28]:
#Exercise 9
def evaluate(board):
    winner = 0
    for player in [1, 2]:
        # Check if `row_win`, `col_win`, or `diag_win` apply.
		# If so, store `player` as `winner`.
        if (row_win(board, player)==True or col_win(board, player)==True or
         diag_win(board, player)==True):
            winner=player
            return(winner)
    if np.all(board != 0) and winner == 0:
        winner = -1
    return winner

evaluate(board)
board


player=[1,2]
results=player+[-1]
board=create_board()
results
player
for j in range(5): #better: while winner==0
    for i in player:
        board=random_place(board,i)
        if (evaluate(board) in results)==True:
            print([board,evaluate(board)])
            break



[array([[0., 1., 2.],
       [0., 0., 2.],
       [1., 1., 2.]]), 2]
[array([[1., 1., 2.],
       [0., 0., 2.],
       [1., 1., 2.]]), 2]
[array([[1., 1., 2.],
       [0., 1., 2.],
       [1., 1., 2.]]), 1]
